# Generated by Django 5.1.1 on 2024-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=None, max_length=100)),
                ('image', models.CharField(blank=None, max_length=500)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
