# Generated by Django 5.1.1 on 2024-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.TextField(blank=None, max_length=500),
        ),
    ]
