# Generated by Django 5.1.1 on 2024-09-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=50)),
                ('address', models.TextField(blank=None, max_length=300)),
                ('phone', models.IntegerField()),
                ('district', models.CharField(blank=None, max_length=50)),
                ('locality', models.CharField(blank=True, max_length=50)),
                ('condition', models.TextField(blank=True, max_length=300)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.service')),
            ],
        ),
    ]
